version: "3.8"

services:
    api:
        build: .
        ports: 
            - 8000:8000
        environment:
            PORT: 8000
            DB_URL: mongodb://mongo_db:27017
            DB_NAME: todos
        volumes:
            - .:/todos
        depends_on:
            - mongo_db    

    mongo_db:
        image: mongo:latest
        ports:
            - 2717:27017 
        volumes:
            - mongo_db:/data/db
volumes:
    mongo_db: